package com.oorbitt.launcher.security

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.InputStream
import java.io.OutputStream
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.CipherInputStream
import javax.crypto.CipherOutputStream
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * AES-256-GCM encryption engine backed by the Android Keystore.
 *
 * Wire format for byte-array operations:
 * ```
 * [ 12-byte IV ][ GCM ciphertext + 16-byte auth tag ]
 * ```
 *
 * Wire format for file / stream operations:
 * ```
 * [ 4-byte IV-length (big-endian int) ][ IV ][ GCM ciphertext + tag ]
 * ```
 * The 4-byte length prefix makes the stream self-describing so
 * [createEncryptedInputStream] can reconstruct the IV without knowing
 * it ahead of time.
 */
class EncryptionEngineImpl : EncryptionEngine {

    companion object {
        private const val KEYSTORE_PROVIDER = "AndroidKeyStore"
        private const val KEY_ALIAS = "oorbitt_vault_key"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
        private const val IV_SIZE_BYTES = 12
        private const val GCM_TAG_BITS = 128
        private const val BUFFER_SIZE = 8_192 // 8 KB streaming buffer
    }

    // ---- key management -----------------------------------------------------

    private fun getOrCreateKey(): SecretKey {
        val keyStore = KeyStore.getInstance(KEYSTORE_PROVIDER).apply { load(null) }

        keyStore.getEntry(KEY_ALIAS, null)?.let { entry ->
            return (entry as KeyStore.SecretKeyEntry).secretKey
        }

        val spec = KeyGenParameterSpec.Builder(
            KEY_ALIAS,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
        )
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(256)
            .build()

        return KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, KEYSTORE_PROVIDER)
            .apply { init(spec) }
            .generateKey()
    }

    // ---- byte-array operations ----------------------------------------------

    override fun encrypt(plainBytes: ByteArray): ByteArray {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, getOrCreateKey())

        val iv = cipher.iv // 12-byte IV generated by the provider
        val cipherText = cipher.doFinal(plainBytes)

        // Prepend IV so the receiver can decrypt without out-of-band IV exchange.
        return iv + cipherText
    }

    override fun decrypt(encryptedBytes: ByteArray): ByteArray {
        require(encryptedBytes.size > IV_SIZE_BYTES) {
            "Encrypted payload too short — expected at least ${IV_SIZE_BYTES + 1} bytes"
        }

        val iv = encryptedBytes.copyOfRange(0, IV_SIZE_BYTES)
        val cipherText = encryptedBytes.copyOfRange(IV_SIZE_BYTES, encryptedBytes.size)

        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.DECRYPT_MODE, getOrCreateKey(), GCMParameterSpec(GCM_TAG_BITS, iv))

        return cipher.doFinal(cipherText)
    }

    // ---- file operations (streaming) ----------------------------------------

    override fun encryptFile(source: File, destination: File) {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, getOrCreateKey())
        val iv = cipher.iv

        FileOutputStream(destination).use { fos ->
            // Write IV length + IV so decryption is self-describing.
            fos.writeInt(iv.size)
            fos.write(iv)

            CipherOutputStream(fos, cipher).use { cos ->
                FileInputStream(source).use { fis ->
                    fis.copyToBuffered(cos)
                }
            }
        }
    }

    override fun decryptFile(source: File, destination: File) {
        FileInputStream(source).use { fis ->
            val ivLen = fis.readInt()
            require(ivLen in 1..256) { "Invalid IV length: $ivLen" }

            val iv = ByteArray(ivLen)
            fis.readExact(iv)

            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.DECRYPT_MODE, getOrCreateKey(), GCMParameterSpec(GCM_TAG_BITS, iv))

            CipherInputStream(fis, cipher).use { cis ->
                FileOutputStream(destination).use { fos ->
                    cis.copyToBuffered(fos)
                }
            }
        }
    }

    // ---- stream factories ---------------------------------------------------

    override fun createEncryptedOutputStream(file: File): OutputStream {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, getOrCreateKey())
        val iv = cipher.iv

        val fos = FileOutputStream(file)
        fos.writeInt(iv.size)
        fos.write(iv)

        return CipherOutputStream(fos, cipher)
    }

    override fun createEncryptedInputStream(file: File): InputStream {
        val fis = FileInputStream(file)

        val ivLen = fis.readInt()
        require(ivLen in 1..256) { "Invalid IV length: $ivLen" }

        val iv = ByteArray(ivLen)
        fis.readExact(iv)

        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.DECRYPT_MODE, getOrCreateKey(), GCMParameterSpec(GCM_TAG_BITS, iv))

        return CipherInputStream(fis, cipher)
    }

    // ---- helpers ------------------------------------------------------------

    /** Write a 32-bit big-endian integer. */
    private fun OutputStream.writeInt(value: Int) {
        write((value shr 24) and 0xFF)
        write((value shr 16) and 0xFF)
        write((value shr 8) and 0xFF)
        write(value and 0xFF)
    }

    /** Read a 32-bit big-endian integer. */
    private fun InputStream.readInt(): Int {
        val b1 = read()
        val b2 = read()
        val b3 = read()
        val b4 = read()
        if (b1 or b2 or b3 or b4 < 0) error("Unexpected end of stream while reading IV length")
        return (b1 shl 24) or (b2 shl 16) or (b3 shl 8) or b4
    }

    /** Read exactly [dst].size bytes or throw. */
    private fun InputStream.readExact(dst: ByteArray) {
        var offset = 0
        while (offset < dst.size) {
            val n = read(dst, offset, dst.size - offset)
            if (n < 0) error("Unexpected end of stream after $offset of ${dst.size} bytes")
            offset += n
        }
    }

    /** Copy this stream to [out] using an 8 KB buffer. */
    private fun InputStream.copyToBuffered(out: OutputStream) {
        val buf = ByteArray(BUFFER_SIZE)
        var bytesRead: Int
        while (read(buf).also { bytesRead = it } != -1) {
            out.write(buf, 0, bytesRead)
        }
    }
}
