package com.oorbitt.launcher.model

data class LauncherSettings(
    val gridColumns: Int = 5,
    val gridRows: Int = 5,
    val dockSlots: Int = 5,
    val drawerColumns: Int = 4,
    val iconSizeDp: Int = 52,
    val labelSizeSp: Int = 12,
    val showLabels: Boolean = true,
    val showDockLabels: Boolean = false,
    val themeMode: ThemeMode = ThemeMode.SYSTEM,
    val iconShape: IconShape = IconShape.CIRCLE,
    val wallpaperDimPercent: Int = 0,
    val searchBarStyle: SearchBarStyle = SearchBarStyle.BAR,
    val sortMode: DrawerSortMode = DrawerSortMode.ALPHABETICAL,
    val activeProfileId: Long = 0,
    val activeIconPack: String? = null,
    val desktopIconSizeDp: Int = 52,
    val drawerIconSizeDp: Int = 52,
    val dockIconSizeDp: Int = 52,
    val showDesktopLabels: Boolean = true,
    val showDrawerLabels: Boolean = true,
    val drawerBgColor: String = "#000000",
    val drawerBgOpacity: Int = 92,
    val drawerBgImage: String? = null,
    val drawerCornerRadiusDp: Int = 0,
    val drawerAnimationType: String = "SLIDE",
    val searchBarPosition: String = "BOTTOM",
    val searchBarCornerRadiusDp: Int = 24,
    val iconCornerTopStart: Int = 50,
    val iconCornerTopEnd: Int = 50,
    val iconCornerBottomStart: Int = 50,
    val iconCornerBottomEnd: Int = 50,
    val iconCornerCut: Boolean = false,
    val drawerCornerTopStartDp: Int = 16,
    val drawerCornerTopEndDp: Int = 16,
    val drawerCornerBottomStartDp: Int = 0,
    val drawerCornerBottomEndDp: Int = 0,
    val drawerSpaceDp: Int = 0,
    val drawerGroupsJson: String = "[]",
    val drawerSearchHeightDp: Int = 48,
    val drawerSearchCornerRadiusDp: Int = 24,
    val drawerSearchBgColor: String = "#FFFFFF",
    val drawerSearchBgOpacity: Int = 12,
    val drawerSearchBorderWidthDp: Int = 0,
    val drawerSearchBorderColor: String = "#FFFFFF",
    val drawerSearchPosition: String = "TOP",
    val appLockTimeoutMs: Long = 0,
    val appLockScreenOff: Boolean = true,
    val appLockBiometricOnly: Boolean = false,
    val dailyScrollLimit: Int = 0,
    val showScrollTrackerWidget: Boolean = false,
    val favoriteAIAppsCsv: String = "",
    val searchResultsSpacingDp: Int = 8,
    val orbSpaceSpacingDp: Int = 16,
    val searchBarPaddingDp: Int = 12,
    val orbSpaceCardCornerRadiusDp: Int = 16,
    val orbSpaceLayoutMode: String = "APPLE_HEALTH",
    val orbSpaceAccentColor: String = "#007AFF",
    val openWithStyle: String = "APPLE_CHIPS",
    val enableWebSearchInOpenWith: Boolean = true,
    val enableAISearchInOpenWith: Boolean = true,
    val showOrbButton: Boolean = true,
    val enableOrbSpace: Boolean = true,
    val lockOrbSpace: Boolean = false,
    val freeFormPlacement: Boolean = false,
    val searchResultBgColor: String = "#1C1C1E",
    val searchResultBgOpacity: Int = 100,
    val searchResultPaddingDp: Int = 12,
    val searchResultTextSizeSp: Int = 14,
    val wellnessWidgetBgOpacity: Int = 40,
    val wellnessWidgetHeightDp: Int = 120,
    val wellnessWidgetCornerRadiusDp: Int = 20,
    val wellnessWidgetAccentColor: String = "#007AFF",
    val hasCompletedOnboarding: Boolean = false
)

enum class ThemeMode { LIGHT, DARK, SYSTEM }

enum class IconShape {
    CIRCLE, SQUIRCLE, ROUNDED_SQUARE, TEARDROP,
    HEXAGON, CLOVER, PEBBLE, IOS_SQUIRCLE
}

enum class SearchBarStyle { BAR, PILL, HIDDEN }

enum class DrawerSortMode { ALPHABETICAL, USAGE, INSTALL_DATE, CUSTOM }
